### ISSUE TITLE
How to validate nested structs?

### ISSUE THREAD

**Issue by roquie** [Blacksmoke16/assert#12]
Like this:

```crystal
class Role
  include Assert

  @[Assert::NotBlank]
  @[Assert::Size(Range(Int32, Int32), range: 4..32)]
  property name : String
end

class Comment
  include Assert

  @[Assert::Size(Range(Int32, Int32), range: 10..5000)]
  property body : String
end

class User
  include Assert

  property role : Role
  property comments : Array(Comment) 
end

User.valid?
```

**Comment by Blacksmoke16** [comment]
You would want to use the [Valid](https://blacksmoke16.github.io/assert/Assert/Assertions/Valid.html) assertion.

Also as a heads up this shard is in the process of being deprecated in favor of https://github.com/athena-framework/validator; however it hasn't reached feature parity yet.  I'm working on adding all the constraints I want to it among other things.  Just something to keep in mind for the future.

**Comment by roquie** [comment]
My bad. Crystal docs is not user friendly ... and `Valid` word in left menu automatically associate in my mind in this context like "just a method who validate object" not a like validate nested objects. Typical mistakes of the mind...

Thanks.
