### ISSUE TITLE
assert(shard.name != "assert")

### ISSUE THREAD

**Issue by didactic-drunk** [Blacksmoke16/assert#6]
I expected to find an [assert](http://man7.org/linux/man-pages/man3/assert.3.html) shard, but this seems more like a validation shard.  The library you based it on also has "validation" in the name.

Do you think the name should change to avoid confusion and maybe make room for assertion style shard?

**Comment by Blacksmoke16** [comment]
You would be correct in thinking this is a validation shard.  However I quite like the name and don't plan to change it.
